apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values: 
          - us-east-1b
        # - key: disktype
        #   operator: In
        #   values: 
        #   - ssd
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preferences:
        matchExpressions:
        - key: project
          operator: In
          values:
          - amazon
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
