apiVersion: v1
kind: Pod

metadata:
  name: multi-containerPort
  labels:
    purpose: multi-containerPort

spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux:9
    image: almalinux:9
    CMD: ["sleep" , "100"]