apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    jenkins-url: "https://jenkins.rohithdevops.com/build/job/5"
    imageregistry: "https://dockerhub.com/"
spec:
  containers:
    - name: nginx
      image: nginx
